#spring.jpa.hibernate.ddl-auto=create
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 252-02-05
  data:
    mongodb:
      uri: mongodb://localhost:27017/local